### PR TITLE
Update OCF servers to the latest JS spec and iotivity v1.3.0

### PR DESCRIPTION
**Pull request by nagineni**
This commit updates all OCF servers to the latest JS spec and
iotivity v1.3.0. It also includes the scripts that are needed to 
create secure configurations.

### CODE REVIEW

**Comment by gvancuts** [comment]
Thanks @nagineni ! I will test this asap (using the Docker containers - now available in `smarthome2cloud/smarthome-[sensors|gateway|cloud]:container-staging`).

One of the three commits is missing the `Signed-off-by` (https://github.com/01org/SmartHome-Demo/pull/174/commits/ddece196fe425e44e2aa2d50ca3a098704a176e3), can you add it?

**Comment by nagineni** [comment]
Thanks @gvancuts. I updated the commit message now.

**Comment by gvancuts** [comment]
Thanks @nagineni ! I will defer to @uhofemei and @ttzeng to determine when to merge this. Am I assuming correctly that the Zephyr-based devices have not been tested with this new version of IoTivity? I would also like to hear from @ttzeng on the readiness of the Android companion app and the JukeBox based on Android Things.

**Comment by gvancuts** [comment]
Thanks @nagineni ! I will defer to @uhofemei and @ttzeng to determine when to merge this. Am I assuming correctly that the Zephyr-based devices have not been tested with this new version of IoTivity? I would also like to hear from @ttzeng on the readiness of the Android companion app and the JukeBox based on Android Things.

**Comment by ttzeng** [comment]
@gvancuts this PR [patches](https://github.com/01org/SmartHome-Demo/blob/2ee59c85ee6eeea917e534efa5267ab93e173ecf/ocf-servers/js-servers/config/json-to-cbor.js#L21) the servers to have an ACE for `coap://` connections, it will be transparent to existing clients, including webUI, iot-rest-api-server, and the Android companion app, while the secured mode is ON, so the current companion app can access to the server as is. Though I only validated with the actual LED server, I believe other servers should be working fine. Having said that, this PR is safe for merging if we want to upgrade to IoTivity 1.3.0 as the 1st step, though we do not take any security features for now.

PS: the servers with [this PR](https://github.com/01org/SmartHome-Demo/blob/2ee59c85ee6eeea917e534efa5267ab93e173ecf/ocf-servers/js-servers/config/security.boilerplate.json#L40) will be in RFOTM state, the coming companion app will be able to move them to RFNOP state. And, the iotivity-node has [an issue](https://github.com/otcshare/iotivity-node/issues/145) while registering secured resources, once we fix this upstream bug, the companion app can be used for pairing the devices and make use of `coaps://` connections.

**Comment by gvancuts** [comment]
Thanks @ttzeng and @nagineni , I'll merge this now!

**Pull request merged**
