### PR TITLE
Add new features and close issue #78

### PR DESCRIPTION
**Pull request by ichbinblau**
1. Load weather and power data automatically in admin portal
2. Pull sensor data when it is not in observable mode
3. Add User: close issue #78 
4. Update user name and password
   dev: P@ssw0rd
   OTC: !otivity
5. Upgrade python version to 2.7.12 in Dockerfile and runtime.txt

**Note**: an new environment is required to run the docker image if it is in a corporate network as the server downloads weather data from external websites.  
eg. docker run -d --name portal --env proxy=**_\<http proxy\>_** -p 3030:3000 -p 3031:4000 smarthome2cloud/portal:weather

### CODE REVIEW

**Comment by qiuzhong** [comment]
Built and tested based on [ichbinblau/load_weather@5bfb554](https://github.com/ichbinblau/SmartHome-Demo/commit/5bfb554dba625a5c7f5a6c4889bf97173fab1f8f)

1 & 2:   I tired both real gateway (MinnowBoard with Intel-IoT-Refkit image#156) and simulated gateway (gvancuts/smarthome-gateway:split-containers from docker hub). There is no OCF sensor displayed in the portal. From the web portal log, I got this error:
```
[2017-03-29 06:12:45,542: ERROR/Worker-3] Failed to get resources: index out of range. 
[2017-03-29 06:12:45,543: ERROR/Worker-3] Failed to get resources: index out of range. 
[2017-03-29 06:12:45,543: ERROR/Worker-3] Failed to get resources: index out of range. 
[2017-03-29 06:12:45,543: ERROR/Worker-3] Failed to get resources: index out of range. 
[2017-03-29 06:12:45,543: ERROR/Worker-3] Failed to get resources: index out of range.
```
This is because policy parameter "p" is recently added to [iot-rest-api-server](https://github.com/01org/iot-rest-api-server/commit/ce21be84dc2d3a03fb99b0756141e29fcbbcb625) but not included in version v0.2.0 that is published to npm repository and widely used at present. So the REST API <code>/oic/res</code> responses will not contain the JSON part
```
"p":{"bm":1,"secure":false}}
```
While the REST client of web portal requires this part. In [RestClient/Resource.py line 56](https://github.com/ichbinblau/SmartHome-Demo/commit/5bfb554dba625a5c7f5a6c4889bf97173fab1f8f#diff-17c3b5f9c88d5629d4f660f12e175f0fR56)
```
bm = item['links'][0]['p']['bm']
secure = item['links'][0]['p']['secure']
```
This will throw <code>KeyError</code>s. With latest iot-rest-api-server, this error is not raised and web portal can function normally.
Maybe we could used <code>dict.get(key)</code> and do a check so there is a fallback if "p" property doesn't exist?

**Comment by qiuzhong** [comment]
3: Adding/Deleting function is supported now. But <strong>User Name is not allowed to edit when updating users</strong> (it's gray and uneditable), @ichbinblau, is this by design?

4 & 5: Verified and applied to the web portal.

**Comment by ichbinblau** [comment]
@qiuzhong  Thanks for the test report.
I have made a quick commit for the improvements you pointed out.  plz check. https://github.com/01org/SmartHome-Demo/pull/125/commits/05ee6b06f0038211d318b2cff72c92541d7a9459 .

**Comment by ttzeng** [comment]
@gvancuts I was wondering the same whether the contained servers can be discovered from the API server on other device? I met the similar issue that the contained servers on Minnowboard can't be discovered by neither the API server running on Ubuntu PC, nor the Android companion app. However, those contained servers are listed in the report from the contained API server on the same Minnowboard.

**Comment by qiuzhong** [comment]
@ichbinblau , with [05ee6b0](https://github.com/01org/SmartHome-Demo/pull/125/commits/05ee6b06f0038211d318b2cff72c92541d7a9459).
* The web portal can handle the REST API responses without policy property "p" from gateway gracefully. The sensors can be displayed now.
* User name field can be editable now.

But there're some tiny widget displaying problems. Here is part of the screenshot (The data is simulated, please just ignore it):
widgets

* Wiget title. 
  You simply concatenate the sensor name and device name for widget titles? This causes widget titles like <strong>SOLAR PANEL TILTSmart Home Solar</strong>. Would you please update it so it can be readable?
* Widgets are not displayed consistently: some sensors are displayed with uuid, some are not. Why?
* SOLAR PANEL TILT percent sign needs to adjust.

**Comment by ttzeng** [comment]
@qiuzhong the ocf-util snaps have been updated with the policy parameter 'p' in the iot-rest-api-server, you could refresh your snap to give it a try...

**Comment by qiuzhong** [comment]
@ttzeng , thanks for your advice. I didn't use ocf-utils snap in the tests above and iot-rest-api-server was set up manually to contain the policy parameter.
It's will be more convenient if iot-rest-api-server is updated in ocf-utils snap. I'll try it.

**Comment by qiuzhong** [comment]
Just tried the latest ocf-util snap and iot-rest-api-server responses do contain the policy parameter part. It will be a handy gateway. Thanks, @ttzeng !

**Comment by ichbinblau** [comment]
Hi, @qiuzhong. Plz see my response below. Thanks 
- Wiget title 
I will try to reproduce it
- Widgets are not displayed consistently: some sensors are displayed with uuid, some are not. Why?
If there are more than one senors of the same type in the dashboard, the uuid + path should be shown in order to differentiate them.  It is a required feature.
- SOLAR PANEL TILT percent sign needs to adjust
Will adjust it.

**Comment by gvancuts** [comment]
> @gvancuts I was wondering the same whether the contained servers can be discovered from the API server on other device? I met the similar issue that the contained servers on Minnowboard can't be discovered by neither the API server running on
> Ubuntu PC, nor the Android companion app. However, those contained servers are listed in the report from the contained API server on the same Minnowboard.

This works when using the 'bridge' network when both containers are on the same machine because both get added to the same subnet (172.17.x.x)... You can make this work (I believe - untested across multiple physical devices) if you use the "--network=host" option when starting the Docker container.

As a side note: I'm wondering if you did not mix this PR up with #83?

**Comment by ttzeng** [comment]
Thanks @gvancuts for the tip -- in order to make the contained servers discovered by OCF clients on other devices, we need to connect the container to the network 'host'.

**Comment by qiuzhong** [comment]
Tested on [b94e3832](https://github.com/01org/SmartHome-Demo/pull/125/commits/b94e832883f2fe33ee7cd539776d1e58eb8f8b0b). The title issue is not reproduced.

**Comment by mjkadera** [comment]
@ttzeng will contact OTC Validation to review items 1 and 2

**Comment by ttzeng** [comment]
@ichbinblau I built the image at [d9b2d2b](https://github.com/01org/SmartHome-Demo/tree/d9b2d2b1292cbb7fdc82f513aac205a5dec5cd58) for verifying the non-observable resources handling, but it does not show resource cards for the MP3 player even though the resources are listed in the iot-rest-api-server report. I have tried CTRL-F5 to clear the cache. Any idea?

**Comment by ichbinblau** [comment]
Hi, @ttzeng.  Would you share the console log from the browser with me by pressing F12? And how many of the jukebox sensors are non observable?

**Comment by ttzeng** [comment]
@ichbinblau please review [this log file](https://github.com/01org/SmartHome-Demo/files/909408/pr125.txt)

**Comment by ttzeng** [comment]
@ichbinblau the [report from the rest-api-server](https://github.com/01org/SmartHome-Demo/files/909433/pr125-api-server-report.txt) and the how it [looks from the web portal](https://cloud.githubusercontent.com/assets/1763431/24852691/013d664e-1e0b-11e7-9874-dbe8b0494128.png)

**Comment by ttzeng** [comment]
@ichbinblau the browser console periodically shows "the brillo component is incomplete" as [this screenshot](https://cloud.githubusercontent.com/assets/1763431/24856226/8ad80e4e-1e16-11e7-9df2-c3b85f5bfdf0.png), FYI

**Comment by ichbinblau** [comment]
@ttzeng , the error message means that not all the Jukebox data was collected. Would you plz unfolder the Object in the console and show me the data under the key "brillo" ?

**Comment by mjkadera** [comment]
@ichbinblau  will work with @ttzeng to troubleshoot the issue

**Comment by ttzeng** [comment]
@ichbinblau please take a look on thisthis

**Comment by ichbinblau** [comment]
Hi, @ttzeng. The log shows that the mp3player data is missing. Would you double check whether the mp3player sensor is accessible in obs mode?( http://192.168.1.106:8000/api/oic/brillo/mp3player?di=3f3b786e-0dbf-47b0-8456-09824d6a04c2&obs=1 )

**Comment by ttzeng** [comment]
@ichbinblau Yes, the API server receives updates whenever there are state changes in the mp3player. The mp3player won't send state updates periodically, so I started the playing from the Android companion app. If the mp3player doesn't change states or the played title, the observers won't receive any updates, so you should query its initial states at the beginning, and keep tracking its states from the received notifications afterward.

**Comment by ttzeng** [comment]
@ichbinblau BTW, they are separate resources in the same device, I'd suggest you twist the logic a liitle bit to treat tham as independent resources even you aggregate them in the same card.

**Comment by ichbinblau** [comment]
HI, @ttzeng I do agree your suggestion that the brillo components should be shown separately.  I have been working on the request. Since there is no emulator for Jukebox, may I validate the update and troubleshoot the incomplete brillo data issue with your gateway like what we did before? Thanks in advance.

**Comment by mjkadera** [comment]
1, 3 and 5 are validated. @ttzeng and @ichbinblau are working on 2.

If a resource is no longer available, the widget will no longer be displayed. The proposal is to show the widget if any feature is reached, but the features that are not reachable will not be controlled in the UI.

**Comment by qiuzhong** [comment]
Just tested the feature:
> 1. Load weather and power data automatically in admin portal

based on ichbinblau@[64def01](https://github.com/ichbinblau/SmartHome-Demo/commit/64def01ce01d31b8ea6209ab01c47423676a043e)
and it can work well.

**Comment by mjkadera** [comment]
All 5 features are validated and ready for final integration for the PR

**Pull request merged**
