### PR TITLE
Need a way to use ADC with Mraa and MinnowBoard

### PR DESCRIPTION
**Pull request by odwdinc**
Created a UPM wrapper for querying ADC values for MinnowBoard MAX

### CODE REVIEW

**Comment by gvancuts** [comment]
Thanks for doing this @odwdinc !

I have a few comments and questions:
- Can you add the copyright and licensing information to this file? (look at the other .js file for an example)
- Can we put this file in a subfolder, e.g. `./helper-function`. I would like to keep this folder with all .js files being standalone OCF servers.
- Can you add a note in the README.md to explain what this does (and the HW it requires)

**Comment by gvancuts** [comment]
Assuming this is specific to the MinnowBoard, can you rename the file from `mraa_Mino_ADC.js` to `mraa_MinnowBoard_ADC.js`?

**Comment by uhofemei** [comment]
Hi @gvancuts the PRs have been updated. Thanks.

**Comment by gvancuts** [comment]
Thanks!

* Can you add the copyright and licensing information to this file? (look at the other .js file for an example)
* Can you add a note in the README.md to explain what this does (and the HW it requires)

**Comment by gvancuts** [comment]
Ping?

**Comment by uhofemei** [comment]
Done. https://github.com/01org/SmartHome-Demo/pull/103

**Comment by gvancuts** [comment]
Obsoleted by #103 - closing

**Pull request closed without merging**
