### PR TITLE
sensors: Support Zephyr v1.7

### PR DESCRIPTION
**Pull request by kiendinh**
All sensors have been confirmed to work with Zephyr v1.7 release.
Thus updated the conditional check in makefiles to make sure they
would be compiled against the Zephyr v1.6 or later.

Signed-off-by: Kien Dinh <kien.t.dinh@intel.com>

### CODE REVIEW

**Comment by gvancuts** [comment]
I have not tested this but 👍 from me.

Do you need to use any particular version of the Zephyr SDK for these? I seem to recall that I had to go back to SDK 0.8.2 in order to build the temperature sensor (possibly because of iotivity-constrained).

**Comment by qiuzhong** [comment]
Tested on Zephyr 1.7 and they both worked well.

The HW is Joule 570x.
The image is [IoT-Refkit image build#138](http://iot-ref-kit.ostc.intel.com/download/builds/intel-iot-refkit_master/2017-03-10_05-58-10-build-138/images/intel-corei7-64/refkit-image-gateway-intel-corei7-64.wic). It doesn't contains the <code>noble</code> module, so I installed it manually.
The Zephyr SDK I used in this test is v0.8.2.

After launching <code>environment_sensor.js</code> or <code>power-uart.js</code> for a while, it can discover the Zephyr sensor service and get sensor data via Bluetooth. And the sensor data is reasonable.
Both OCF client apps for smartphone and iot-rest-api-server can discover the OCF devices and resources.

**Comment by gvancuts** [comment]
Could you (or someone) also independantly validate the new OCF temperature sensor?

**Comment by qiuzhong** [comment]
I've tried many times on Arudino 101 board to see if the OCF temperature sensor can work with Zephyr 1.7. But I didn't go far as the bluetooth 6lowpan network was not set up. 
There're disconnection problems:
* The Ubuntu host failed to connect to the Arudino 101 board
  In this case, I didn't see the <code>bt0</code> in the output of command <code>ifconfig</code>.
* The Ubuntu host could easily disconnect to the Arudino 101 board.
  Occasionly, the <code>bt0</code> appeared after running <code>ifconfig</code>. But when I was checking the OCF resources via the REST API, it couldn't be found. Then I checked with command <code>ifconfig</code>, the <code>bt0</code> disappeared.

I simply follow the [README](https://github.com/01org/SmartHome-Demo/blob/master/sensors/ocf_temperature_sensor/README.md) of OCF temperature sensor. The Ubuntu host can discover the OCF temperature sensor soon via the <code>bluetoothctl</code> utility.

Here is my configuration:
* HW: Joule + Arudino 101
* Host: Joule with Ubuntu 16.04 LTS
* [iotivity-contrained@3b03b0b](https://github.com/iotivity/iotivity-constrained)
* zephyr 1.7 (bdc3107d5c47d9cf4b6a4e948186a0a2730d92c5)

@kiendinh, could you please take a look and give me some suggestion? What're the possible causes of the disconnection?

**Comment by qiuzhong** [comment]
I also tried switching zephr to the master branch(cb2ae52faec54ca8ff9ba54d51add85c7bae3300). But the result was the same.

**Comment by qiuzhong** [comment]
I could go through last time after [PR#94](https://github.com/01org/SmartHome-Demo/pull/94) is merged. But it didn't specify a fixed commit id or tag for the zephyr in README. It just say <strong>master branch</strong> of zephyr at that time. Unfortunately, I updated my local zephr repository and I don't know how to revert to last status.

**Comment by kiendinh** [comment]
I'll get back to you soon, @qiuzhong. There is something else that keeps me busy recently.

**Comment by qiuzhong** [comment]
It turns out that the Bluetooth firmware needs to update.

After building and flashing the Bluetooth firmware (samples/bluetooth/hci_uart) based on Zephyr v1.7.0, the bluetooth_6lowpan can be set up and keep much more stable. The temperature resource can be discovered and the sensor data is reasonable.

```
root@joule-Broxton-M:/home/joule/Downloads/01org/iot-rest-api-server/test# ./oic-get /d
localhost:8000 /d
[{"di":"c5e05609-33e1-4609-61e1-56090fe25609","n":"Kishen's thermostat","icv":"1.0"}]
HTTP: 200
root@joule-Broxton-M:/home/joule/Downloads/01org/iot-rest-api-server/test# ./oic-get /p
localhost:8000 /p
[{},{"pi":"cb935609-3b94-4609-6994-560917955609","mnmn":"Intel"}]
HTTP: 200
root@joule-Broxton-M:/home/joule/Downloads/01org/iot-rest-api-server/test# ./oic-get /res
localhost:8000 /res
[{"di":"b2f02068-6958-49fa-b77d-4ea733a496b2","links":[{"href":"/oic/sec/doxm","rt":"oic.r.doxm","if":"oic.if.baseline","p":{"bm":1,"secure":false}}]},{"di":"b2f02068-6958-49fa-b77d-4ea733a496b2","links":[{"href":"/oic/sec/pstat","rt":"oic.r.pstat","if":"oic.if.baseline","p":{"bm":1,"secure":false}}]},{"di":"b2f02068-6958-49fa-b77d-4ea733a496b2","links":[{"href":"/oic/d","rt":"oic.wk.d","if":"oic.if.baseline","p":{"bm":1,"secure":false}}]},{"di":"b2f02068-6958-49fa-b77d-4ea733a496b2","links":[{"href":"/oic/p","rt":"oic.wk.p","if":"oic.if.baseline","p":{"bm":1,"secure":false}}]},{"di":"9cabb1bf-b991-42c8-bf6e-14a6a987b84d","links":[{"href":"/oic/sec/doxm","rt":"oic.r.doxm","if":"oic.if.baseline","p":{"bm":1,"secure":false}}]},{"di":"9cabb1bf-b991-42c8-bf6e-14a6a987b84d","links":[{"href":"/oic/sec/pstat","rt":"oic.r.pstat","if":"oic.if.baseline","p":{"bm":1,"secure":false}}]},{"di":"9cabb1bf-b991-42c8-bf6e-14a6a987b84d","links":[{"href":"/oic/d","rt":"oic.wk.d","if":"oic.if.baseline","p":{"bm":1,"secure":false}}]},{"di":"9cabb1bf-b991-42c8-bf6e-14a6a987b84d","links":[{"href":"/oic/p","rt":"oic.wk.p","if":"oic.if.baseline","p":{"bm":1,"secure":false}}]},{"di":"c5e05609-33e1-4609-61e1-56090fe25609","links":[{"href":"/oic/p","rt":"oic.wk.p","if":"oic.if.r","p":{"bm":1,"secure":false}}]},{"di":"c5e05609-33e1-4609-61e1-56090fe25609","links":[{"href":"/oic/d","rt":"oic.d.thermostat","if":"oic.if.r","p":{"bm":1,"secure":false}}]},{"di":"c5e05609-33e1-4609-61e1-56090fe25609","links":[{"href":"/a/temperature","rt":"oic.r.temperature","if":"oic.if.r","p":{"bm":3,"secure":false}}]}]
HTTP: 200
root@joule-Broxton-M:/home/joule/Downloads/01org/iot-rest-api-server/test# ./oic-get /a/temperature?di=c5e05609-33e1-4609-61e1-56090fe25609
localhost:8000 /a/temperature?di=c5e05609-33e1-4609-61e1-56090fe25609
{"temperature":70.9967444,"units":"F","range":"-40, 257"}
HTTP: 200
```

**Comment by qiuzhong** [comment]
Based on the tests above, I think the OCF temperature sensor also supports Zephyr v1.7.0

**Comment by gvancuts** [comment]
Thanks @qiuzhong , I'll merge this then! 👍

**Comment by mjkadera** [comment]
Next step is to create the test plan for the multiple sensors and migrate the devices

**Pull request merged**
