### PR TITLE
Enabling BLE connectivity to the DC power meter

### PR DESCRIPTION
**Pull request by kiendinh**
The DC power meter now can use BLE (default) or UART (if BLE doesn't exist) to communicate with the home gateway.

### CODE REVIEW

**Comment by kiendinh** [comment]
@gvancuts, @poussa Could you please have a look? Thanks.

**Comment by gvancuts** [comment]
This looks good to me with a couple of comments before merging:
1. Can someone test this independantly ( @ttzen, @uhofemei , anyone else...)?
2. The PR is showing quite a number of commits which are unrelated to the feature. I believe this is an artefact of how you've maintained your forked version of SmartHome-Demo, kept it up-to-date, created and pushed the PR. Can you take a look here to see if that helps you prepare a cleaner PR: https://ostroproject.org/documentation/quick_start/contributor-guide.html#prepare-your-patch ?

Thanks!

**Comment by uhofemei** [comment]
The demo kit is still in-transit. When it's back in Oregon I can test this.

**Comment by kiendinh** [comment]
Alright. I'll close this one and re-push a clean one.

**Pull request closed without merging**
