### PR TITLE
 Call subscribe() method to enable global presence flag

### PR DESCRIPTION
**Pull request by nagineni**
Call subscribe() method to enable global presence, so that the client will receive device presence notifications "added", "deleted", "changed"

Signed-off-by: Sudarsana Nagineni <sudarsana.nagineni@intel.com>

### CODE REVIEW

**Comment by nagineni** [comment]
@poussa @gvancuts

**Comment by gvancuts** [comment]
LGTM but I haven't tested this

**Comment by nagineni** [comment]
Tested this with the latest iotivity-node and it working fine.

**Comment by poussa** [comment]
LGTM !

**Pull request merged**
