### PR TITLE
ocf-servers: Exit OCF servers gracefully

### PR DESCRIPTION
**Pull request by nagineni**
Exit OCF servers gracefully by cleaning up all registered handlers when interrupted.

Signed-off-by: Sudarsana Nagineni <sudarsana.nagineni@intel.com>

### CODE REVIEW

**Comment by nagineni** [comment]
@uhofemei @gvancuts PTAL

**Comment by gvancuts** [comment]
I have not tested this but 👍 from my side

**Comment by uhofemei** [comment]
It doesn't seem to be working as expected. Scenario: systemctl stop fan; systemctl start fan; and using the observer URL for fan I still see: Resource retrieve failed: retrieve: OCDoResource response failed. The observer page doesn't become functional again util I restart the rest-api-server.

**Comment by nagineni** [comment]
You don't need to restart the REST API server. Just do the resource discovery after restarting the fan using systemctl.

Check the relevant discussion here: https://github.com/01org/SmartHome-Demo/issues/77

**Comment by uhofemei** [comment]
I see the device appearing again in the resource table, but the observer mode for this device doesn't work until I restart the rest API service.

I'll read the thread you pointed me to.

Thanks.

Ulf

On Jan 20, 2017 1:11 AM, Sudarsana Nagineni <notifications@github.com> wrote:

You don't need to restart the REST API server. Just do the resource discovery after restarting the fan using systemctl.

Check the relevant discussion here: #77<https://github.com/01org/SmartHome-Demo/issues/77>

**Comment by nagineni** [comment]
Replaced by #90

**Pull request closed without merging**
