### PR TITLE
smarthome-companion: initial check-in of Android companion app

### PR DESCRIPTION
**Pull request by ttzeng**
This commit adds the Android companion app to the IoT-to-Cloud Smart Home demo. The companion app invokes native [IoTivity base Android API](https://api-docs.iotivity.org/latest-java/index.html) to discover and communicate with OCF servers set up in the demo, as well as some provisioning functions to act as a simple on-boarding tool for the demo.

Signed-off-by: Tonny Tzeng tonny.tzeng@intel.com

### CODE REVIEW

**Comment by SteveAtSentosa** [comment]
Hi Tonny,

As soon as you merge this PR, I will try to build and run

Steve
CableLabs

**Comment by gvancuts** [comment]
Thanks for the PR @ttzeng .

@SteveAtSentosa , I typically wait until I get the green light from someone else who's tested the code before merging. I'll check if some of the usual suspects who've been working on the demo can verify this PR. If you'd like to help with that, it would be a great help. You can already checkout the code as follows:
```
git fetch origin pull/186/head:android-companion-app
git checkout android-companion-app
```
(*note*: I used `android-companion-app` as the branch name above but you can use whatever else you like)

**Comment by gvancuts** [comment]
Is there anyone who could test this PR please?

**Comment by thiagogcm** [comment]
I can take a look this weekend =)
Meanwhile.. Why don't you provide the iotivity .aar with the app?

**Comment by ttzeng** [comment]
@thiagogcm thanks for giving it a try. As there are restrictions to publicly release prebuilt binaries, we expect the .aar libraries should be built from the [IoTivity releases](https://www.iotivity.org/downloads/iotivity-1.3.0), and checked in to your local maven repository. :)

**Comment by thiagogcm** [comment]
I've just tried some functions, not a full explore though.
I ran on the emulator because I don't have a physical device available at the moment. I can try again during the week..

Some issues I found so far:

* Provisioning crashes the app
Cause: ```Discovering device error: org.iotivity.base.OcException: Failed to get Device Status List PDM_IS_NOT_INITIALIZED```

* Audio Control / MP3 player does not show anything

* Clicking on Button, the refresh button, then button again, then refresh and finally button again crashes de app
cause: https://pastebin.com/QzR2McFR

* Choosing the PUT option raises an exception:
```Failed to GET representation [JNI_INVALID_VALUE] org.iotivity.base.OcException: stack error in onPutCallback JNI_INVALID_VALUE```

**Comment by ttzeng** [comment]
@thiagogcm thanks for providing feedbacks, I'll take a look. From the log file, it seems you have two button resources hosted, are you using [this button resource](https://github.com/01org/SmartHome-Demo/blob/master/ocf-servers/js-servers/button.js) server?

Regarding the provisioning crash, are you see the issue consistently, as I didn't see the PDM_IS_NOT_INITIALIZED error in the log, and PDM should be [initialized ]([url](            OcProvisioning.provisionInit(sqlDbFilename);))when the app is started, or did you build the AAR library or which IoTivity commit did you base off?

Regarding the Audio control/MP3 player resources, they are physical IoTivity native app running on Android Things, we don't have simulator for that.

The PUT option is a workaround when [iotivity-node updated resources with PUT request](https://github.com/01org/SmartHome-Demo/issues/41), instead of POST request called out in the spec, but that is not the root cause. It looks like the ''value' property of the button resource is not a boolean number, we'll need to look into the button resource implementation as well.

**Comment by xiaoyu3x** [comment]
@ttzeng 
Sorry,add comments late. 
Four target_arch 'x86, x86_64, armeabi,armeabi_v7a' aar packages are build successfully, but they build fail in andriod studio. 
The following are two error info:
1. 
```
Error:(139, 60) error: unreported exception OcException; must be caught or declared to be thrown
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
Information:BUILD FAILED
```
[iotivity-build_armeabi_v7a.log](https://github.com/01org/SmartHome-Demo/files/1386979/iotivity-build_armeabi_v7a.log)

2.
```
AGPBI: {"kind":"error","text":"Error retrieving parent for item: No resource found that matches the given name \u0027android:TextAppearance.Material.Widget.Button.Inverse\u0027.","sources":[{"file":"/home/hj/iot/ww/ww41/SmartHome-Demo/smarthome-companion/app/build/intermediates/res/merged/debug/values-v23/values-v23.xml","position":{"startLine":3}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"Error retrieving parent for item: No resource found that matches the given name \u0027android:Widget.Material.Button.Colored\u0027.","sources":[{"file":"/home/hj/iot/ww/ww41/SmartHome-Demo/smarthome-companion/app/build/intermediates/res/merged/debug/values-v23/values-v23.xml","position":{"startLine":33}}],"original":"","tool":"AAPT"}
/home/hj/iot/ww/ww41/SmartHome-Demo/smarthome-companion/app/build/intermediates/res/merged/debug/values-v23/values-v23.xml:4: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Inverse'.
/home/hj/iot/ww/ww41/SmartHome-Demo/smarthome-companion/app/build/intermediates/res/merged/debug/values-v23/values-v23.xml:34: error: Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Button.Colored'.
FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt
```
[iotivity-build.log](https://github.com/01org/SmartHome-Demo/files/1386981/iotivity-build.log)


The two error difference may be caused by the MVN installation.
This is different point:
selection_020

Why build fail, I don't know.
Why have different error , I don't know too.
Please, help to analyse them.

**Comment by ttzeng** [comment]
@xiaoyu3x thanks for providing feedbacks. One question: which IoTivity code base did you base off to generate the .aar libraries? If you generated the .aar libraries from the cloned [git repo](https://gerrit.iotivity.org/gerrit/p/iotivity.git), did you checkout the '1.3.0' branch? There was [a bug](https://jira.iotivity.org/browse/IOT-2594) in the getLinkDevices() Java API, which might be related to your 1st failure (if your Android Studio indicates the error is at [here](https://github.com/01org/SmartHome-Demo/blob/bc967ce44441e138397651cf364bae3a64a8d662/smarthome-companion/app/src/main/java/com/intel/otc/iot/smarthome/ProvisioningManagerFragment.java#L139)).

Regarding the 2nd failure, it seems related to the Android Studio build environment. Would you please do a clean build and check whether the Android SDK was installed successfully?

**Comment by xiaoyu3x** [comment]
@ttzeng 
Thank your answer, I build APK  and install it to nexus 5.
I flash [led.js](https://github.com/01org/SmartHome-Demo/blob/master/ocf-servers/zjs-servers/led.js) into Arduino101 and connect smarthome-companion by bluetooth on phone.
But, they disconnect for a second.
1. Provisioning crashes the app
2. Smart Home 3D--->'Webpage not available' http://0.0.0.0:8080/ could not be loaded because: net::ERR_CONNECTION_RFUSD
3. Audio Control / MP3 player does not show anything

**Comment by ttzeng** [comment]
@xiaoyu3x glad you successfully built the APK, however please do not test with the iotivity-constrained based ZJS server unless we are sure the integrated iotivity-constrained has secure mode enabled. Besides, ZJS connections are through 6lowpan, which are different than the BLE characteristics based native IoTivity implementation. I'd suggest to test the ownership transfer with [this pseudo server](https://github.com/ttzeng/node-examples/blob/master/iotivity-node/tools/binarySwitch.js) or [this Edison LED server](https://github.com/ttzeng/node-examples/blob/master/iotivity-node/led.js) first, then configure the server's SVR DB file and verify the ACL function.

Regarding the 'Smart Home 3D' option, if you have the [smarthome-gateway](https://github.com/01org/SmartHome-Demo/tree/master/gateway) running, you could enter the IP address of the gateway, that option will display the WebGL based 3D dollhouse through the WebView widget.

The Audio / MP3 player option will discover the OCF audio control resource and the proprietary MP3 player resource implemented in our Android Things based Jukebox demo if you have one. :)

**Comment by xiaoyu3x** [comment]
Thanks @ttzeng 
Unfortunately, I don't have Edison images about iotivity 1.3.0 , So can you give me  a image?

**Comment by ttzeng** [comment]
@thiagogcm @xiaoyu3x I found the root cause why the companion app crash at the end of provisioning and throw the PDM_IS_NOT_INITIALIZED error --- it's because Android 6.0+ enforce the app permission acknowledge, you will have to go to Settings -> Apps -> SmartHome Companion -> Permissions and grant the Storage access manually, so that the companion app can access the provisioning and SVR DB files from the sdcard.

**Comment by ttzeng** [comment]
Please review the new approach of building the Companion app in a container, so that it can pull and build the IoTivity Android library automatically in a deterministic way.

**Comment by gvancuts** [comment]
Great stuff @ttzeng . I haven't tested it myself but I really like the approach so 👍 from me. It would be great if someone could validate this so we can merge this PR.

**Comment by xiaoyu3x** [comment]
hi, @ttzeng 
Sums up, so far as  there are 13 functions run normally.
Normal Functions List:
```
Provisioning
Cloud Management Console
PIR Motion
MQ2 Gas Sensor
Ambient Light
Button
Fan
LED
Buzzer
LCD Backlight
Environmental sensor
Power Meter
Solar Panel
```
There are 2 functions can't verify as lack devices:
```
Audio Control
MP3 Player
```
There are 2 functions exist issue:
`Smart Home 3D`  Webpage loaded unsuccessfully after set ip address.
`Cloud Admin Portal` can't access even if input correct username/password.

**Comment by gvancuts** [comment]
Thank you for testing this @xiaoyu3x!

> There are 2 functions can't verify as lack devices:
> `Audio Control`
> `MP3 Player`

Unless someone comes forward with an offer to test these, my proposal is that we consider these as non-blocking for a merge. Raise your hand anyone if you disagree.

> There are 2 functions exist issue:
> `Smart Home 3D` Webpage loaded unsuccessfully after set ip address.

Are you able to see it outside of the Android app (using the IP address directly)? If not, make sure this is effectively running. The way we run the `gateway-server.js` code in Docker for example is with the `-r` argument which only enables the rules engine, **not** the 3D UI.

> `Cloud Admin Portal` can't access even if input correct username/password.

That one is odd... is there any error message or log you can send us?

**Comment by xiaoyu3x** [comment]
hello, @gvancuts 
According to your comment, I retest 'Smart Home 3D'
1.[Native installation](https://github.com/01org/SmartHome-Demo/tree/master/gateway#native-installation) and run gateway-server.js with the `-r` argument
selection_035
2. Start `The IoT REST API Server`
3. Access gateway-server(http://192.168.1.20:8000/api/system) by phone's chrome browser
screenshot_20171105-213411
4. Access gateway by 'Smart Home 3D' button of SmartHome Companion app.
screenshot_20171105-213355
Why get "No request handler for /" and is it right result?
I get the same to output info from `The IoT REST API Server` console
selection_034
The following is adb log.
[adb_3d_1.txt](https://github.com/01org/SmartHome-Demo/files/1444857/adb_3d_1.txt)

Please help me checking this.

**Comment by ttzeng** [comment]
@xiaoyu3x thanks for following up this PR.
Regarding the 3D home model, as @gvancuts pointed out, you will need to remove the "-r" argument in order to enable the websocket handling in the Gateway. For instance, if you want to run the containerized Gateway, you will need to specify the container entrypoint explicitly:
`sudo docker run -it --rm -p 8080:8080 --entrypoint bash smarthome2cloud/smarthome-gateway -c "node /opt/SmartHome-Demo/gateway/gateway-server.js"`
you should be able to manipulate the 3D house model in the Companion app.

Regarding the cloud portal admin page, the 'admin/admin' credential should work (it works for me). Be sure you enter the 'admin' in lowercase, as Android will default change to uppercase for getting the login name.

Regarding "No request handler for /", you might check the Port is configured properly after clicking 'Smart Home 3D' item. It seems you were accessing to the iot-rest-api-server, instead of the Gateway.

**Comment by xiaoyu3x** [comment]
hello, @ttzeng 
Thanks to your help, I had tested successfully to 'Smart Home 3D' and 'Cloud Admin Portal'.
Smart Home 3D:
capture


Cloud Admin Portal:
capture1
capture2

I found a new issue #188 and perhaps it has useful to set gateway.
Moreover the interface of cloud admin portal is very confused.

**Comment by gvancuts** [comment]
Thank you all for your testing! I will merge this PR shortly now that these issues are resolved. #188 is tracked separately and PR #189 has been submitted to fix it.

We will have to test `Audio Control` and `MP3 Player` independently and file issues accordingly.

**Pull request merged**
