### PR TITLE
documentation: improve OCF JavaScript Servers README.md

### PR DESCRIPTION
**Pull request by gvancuts**
Add more details and pictures to the OCF JavaScript Servers
README.md file (in ocf-servers/js-servers) to explain how
the Smart Solar Panel is physically mounted and how the
associated OCF server can be started.

Signed-off-by: Geoffroy Van Cutsem geoffroy.vancutsem@intel.com

### CODE REVIEW

**Comment by gvancuts** [comment]
@ttzeng @kiendinh , can you please take a look?

All others, you're welcome to comment too of course ;-)

**Comment by gvancuts** [comment]
I have force-pushed a new revision of this PR, hopefully addressing all comments. Please take a look!

**Comment by kiendinh** [comment]
LGTM

**Comment by gvancuts** [comment]
@ttzeng , any further comment or are you good if I merge this?

**Comment by ttzeng** [comment]
LGTM

**Comment by gvancuts** [comment]
Thanks, merging!

**Pull request merged**
