### PR TITLE
Implement sensor servers using Soletta I/O Node.js bindings

### PR DESCRIPTION
**Pull request by nagineni**
This branch includes the implementation of GPIO and AIO based sensor servers using Soletta I/O Node.js bindings.

Signed-off-by: Sudarsana Nagineni <sudarsana.nagineni@intel.com>

### CODE REVIEW

**Comment by gvancuts** [comment]
I have not tested this but this looks good to me.

Just to make sure I understand it correctly, it does not (yet?) use Soletta OCF's implementation?

**Comment by nagineni** [comment]
@gvancuts Thanks for looking into this.

> I have not tested this but this looks good to me.

I've been testing these sensors with the demo setup we have here and the outcome is exactly as same as the sensors based on mraa.

> Just to make sure I understand it correctly, it does not (yet?) use Soletta OCF's implementation?

You are right. These are still based on the iotivity-node. I will update to Soletta OCF implementation, once the bindings are ready.

**Comment by nagineni** [comment]
@poussa

**Comment by nagineni** [comment]
@gvancuts Could you please merge this?

Thanks!

**Comment by gvancuts** [comment]
@poussa , OK to merge?

**Comment by poussa** [comment]
LGTM. I like the idea we keep both versions in separate directories

js-servers: mraa and iotivity-node
soletta-js-servers: soletta HW and soletta OCF (once ready)

**Comment by gvancuts** [comment]
I fully concur, merging.

/me also making a mental note that it'll soon be time to update the top-level README.md to decribed this new folder (and also the ostro-config/systemd-services folder which we do not talk about).

**Pull request merged**
