### PR TITLE
Upgrade demo to iotivity-node v1.1.0 and latest JS API spec

### PR DESCRIPTION
**Pull request by nagineni**
This branch contains the changes that are needed to run the demo based on iotivity-node v1.1.0 and latest JS API spec.

Signed-off-by: Sudarsana Nagineni <sudarsana.nagineni@intel.com>

### CODE REVIEW

**Comment by nagineni** [comment]
@poussa @gvancuts @uhofemei

**Comment by poussa** [comment]
Looks good, did not test. +1 for merging.

**Comment by nagineni** [comment]
@gvancuts Could you please have a look and merge this PR?

**Comment by gvancuts** [comment]
:+1: merging

**Pull request merged**
