### PR TITLE
Re-organise repository: remove obsolete code and promote new codebase

### PR DESCRIPTION
**Pull request by gvancuts**
Remove demo code that is obsolete and no longer maintained (pre-1.0.0
IoTivity code). It can still be found in the "smarthome-iotivity-pre-1.0.0"
tag. Promote new codebase to the top-level folder.

Signed-off-by: Geoffroy Van Cutsem <geoffroy.vancutsem@intel.com>

### CODE REVIEW

**Comment by gvancuts** [comment]
@uhofemei @poussa @nagineni @kiendinh 

Please take a look

**Comment by nagineni** [comment]
LGTM. Thanks, @gvancuts 

How about re-naming dollhouse to something like model-ui in the top level directory?

**Comment by gvancuts** [comment]
I think this is a good suggestion, how about we make that name gateway-webui instead?

**Comment by gvancuts** [comment]
Force-pushed an update (renaming dollhouse into gateway-webui)

@uhofemei @poussa @nagineni @kiendinh Please take a look

**Comment by poussa** [comment]
Looks good. Lets merge !

**Comment by nagineni** [comment]
:+1:

**Pull request merged**
