### PR TITLE
Update client and servers implementation to IoTivity 1.1.1

### PR DESCRIPTION
**Pull request by nagineni**
This updates the client and servers implementation to IoTivity 1.1.1.

Signed-off-by: Sudarsana Nagineni <sudarsana.nagineni@intel.com>

### CODE REVIEW

**Comment by nagineni** [comment]
@poussa @gvancuts @uhofemei PTAL

**Comment by poussa** [comment]
What happens if you dont set the coreSpecVersion and dataModels variables?

**Comment by nagineni** [comment]
Unfortunately coreSpecVersion and dataModels are not an optional attributes and server(s) will throw TypeError while setting the device info.

@zolkis should we mark them as optional in OicDevice info?

**Comment by zolkis** [comment]
> What happens if you dont set the coreSpecVersion and dataModels variables?

AFAIK a device always needs to set these, since it's needed for the OCF certification (i.e. against which spec version and data model it is certified).

**Comment by poussa** [comment]
OK, they are mandatory and code throws exception if they are not set. That is all clear now.

+1

**Comment by gvancuts** [comment]
:+1:

**Pull request merged**
