### PR TITLE
Add Bluetooth BLE support to the snap

### PR DESCRIPTION
**Pull request by ttzeng**
Add BLE supports to the snap, including [noble] and [bleno] node.js libraries, and the `rfkill` and `hciconfig` Linux command line tools for enabling the Bluetooth interface.

[noble]: https://github.com/sandeepmistry/noble
[bleno]: https://github.com/sandeepmistry/bleno

### CODE REVIEW

**Comment by gvancuts** [comment]
Thanks @ttzeng , this is a very useful feature! This looks good to me, could someone please test and verify this?

**Comment by poussa** [comment]
I tried this but could not figure out how to connect to the BLE peripheral.

That is, the missing commands are:

````
sudo bluez.bluetoothctl
...
[NEW] Device FB:13:A4:6A:E0:9F Test IPSP node
...
[bluetooth]# exit
````
And then:
```
sudo echo "connect FB:13:A4:6A:E0:9F 2" >/sys/kernel/debug/bluetooth/6lowpan_control
```

However, you can't access the `/sys/kernel/debug` in snappy. You get access defined whatever your do.

**Comment by gvancuts** [comment]
@poussa , I've done a quick grep through the [snapd](https://github.com/snapcore/snapd/) source code and from what I can see there is no interface that can allow a snap to touch `/sys/kernel/debug/bluetooth`. The closest example is the `system-trace` interface but even that one gives you access only to `kprobes` and `tracing` in that folder.

Is this the only way we can connect a 6LowPAN device?

**Comment by gvancuts** [comment]
Hi again @poussa , was that using Ubuntu Core or Ubuntu Desktop?

Note that in @ttzeng 's case, we're not using 6LowPAN yet. The OCF server we have at the moment get the data from the Arduino 101 board over GATT.

**Comment by gvancuts** [comment]
@poussa , have you been able to use this in the end?

**Comment by poussa** [comment]
We just got a fix in the iotivity-node. Need to test it....

**Comment by wanghongjuan** [comment]
Hi, @gvancuts I just build this BLE snap and find that there is a different point when run command `snap interfaces iotivity-smarthome-demo`, following the README file, should show the `bluez` information as below:
```
$ snap interfaces iotivity-smarthome-demo
Slot           Plug
bluez:service  bluez:client,iotivity-smarthome-demo:bluez
...
```
but I get
```
Slot           Plug
-              iotivity-smarthome-demo:bluez
...
```
Commands `rfkill`, `hciconfig` and `run-gateway-server` can work well, but I don't connect the bluetooth to get data from Arduino 101, since this snap is not contain iotivity-node.

**Comment by poussa** [comment]
You need to connect the snap interfaces and slots:

```bash
$ snap connect iotivity-smarthome-demo:bluetooth-control
$ snap connect iotivity-smarthome-demo:network-control
```

**Comment by ttzeng** [comment]
@wanghongjuan , which platform did you install the snap? it looks like your platform does not have snap providing bluez slot, you may need to `snap install bluez` to install the slot.

This snap only exposes commands to enable the hci interface, future commit will define `node` command with the right environment setup (similar as the `run-gateway-server` command) for running specific scripts.

**Comment by gvancuts** [comment]
Is there something out of that conversation that we should insert into the README file to improve the documentation?

**Comment by wanghongjuan** [comment]
@poussa I have been run the two commands and got same information as README file, just the `bluez` information is different.
@ttzeng I'm using Snappy Ubuntu Core(16.04.1) with Joule 570x, when executing command `snap install bluez`, the system reminder `error: cannot install "bluez": snap "bluez" already installed`

**Comment by ttzeng** [comment]
@wanghongjuan it looks like the bluez interface is not auto connect on Joule. I think you would need `snap connect iotivity-smarthome-demo:bluez bluez` to connect the plug manually.

**Comment by wanghongjuan** [comment]
Thanks @ttzeng , it works now. I think the README file should add this command, since the README describes the snap that can run the Smart Home gateway functionthe on Intel Joule Development Kit running Ubuntu Core.

**Comment by ttzeng** [comment]
Thanks for the confirmation, @wanghongjuan , I'll update the README as suggested. However, it's interesting! I just install the snap (from the store) on my Joule board, the bluez interface is auto connected... I assume you installed your built snap locally, would you do me a favor to try `snap install iotivity-smarthome-demo --edge` and see whether the interface will be auto connected?  Thanks.

**Comment by ttzeng** [comment]
Sorry, I'd like to close this one and submit a new PR, as I was unable to amend the previous PR.

**Comment by wanghongjuan** [comment]
@ttzeng I tried to install the snap using command that you mentioned, the interface `bluez` won't connect automatically, need to connect it manually.

**Pull request closed without merging**
