### PR TITLE
Make buzzer sensor controllable via the Cloud portal.

### PR DESCRIPTION
**Pull request by ichbinblau**
Close issue #122.

Signed-off-by: Theresa <theresa.shan@intel.com>

### CODE REVIEW

**Comment by qiuzhong** [comment]
Built and tested with [ichbinblau@b4a76b9](https://github.com/ichbinblau/SmartHome-Demo/commit/b4a76b955b9f23fd17676968f8c8b1766713b417) on phyical gateway and it can work. 
The buzzer is controllable in the web portal now. Here is the screenshot:

**Comment by qiuzhong** [comment]
This PR seems has the same rebase as [PR#125](https://github.com/01org/SmartHome-Demo/pull/125). Some files are updated in both PRs. It might raise conflicts when merging them.

**Comment by mjkadera** [comment]
Ready to be merged but it could impact the diff file with PR#125. Will need to rebase PR#125.

**Comment by gvancuts** [comment]
Thanks for the validation @qiuzhong , merging

**Pull request merged**
