### PR TITLE
Set correct type for the 'range' & 'rgbValue' properties of Color RGB resource

### PR DESCRIPTION
**Pull request by ttzeng**

### CODE REVIEW

**Comment by nagineni** [comment]
LGTM. 

Nice that it has been changed from string to array in the latest data model http://oneiota.org/revisions/1414

**Comment by gvancuts** [comment]
Thank you both. Does that require any changes anywhere else (e.g. web portal code)?

**Comment by nagineni** [comment]
Yes, probably in the Cordova android app. No changes required in the web portal code.

**Comment by gvancuts** [comment]
OK, so no further changes should be made on this repo to keep things working. I'll merge it. Thanks

**Pull request merged**
