### PR TITLE
Upgrade iot-rest-api-server and iotivity-node packages

### PR DESCRIPTION
**Pull request by gvancuts**
This brings the version of the iot-rest-api-server and
iotivity-node to, respectively, 0.3.0 and 1.2.0-2. Where
the iot-rest-api-server is installed (e.g. gateway), the
version of iotivity-node is no longer specified directly
but will instead be derived automatically by npm.

Signed-off-by: Geoffroy Van Cutsem <geoffroy.vancutsem@intel.com>

### CODE REVIEW

**Comment by ttzeng** [comment]
lgtm, and this reminds me the iot-rest-api-server has been advanced to 0.3, I'll update the prebuilt snap accordingly.

**Comment by gvancuts** [comment]
Hi @ttzeng , thanks for yout :+1: ! Have you tested this or simply visually inspected the changes?

:+1: on updating your prebuilt snap too ;-)

**Comment by ttzeng** [comment]
@gvancuts I only inspected the changes, as I doubt we could 'npm install' to get the required modules in place on our traget platforms. Enlight me please~

**Comment by gvancuts** [comment]
Why couldn't we use `npm install` on the target? The key is of course to use an OS on the target that not only provides `npm` but also includes all the dependencies to build `iotivity` from scratch... but you're right in the sense that we never use it this way.

Those files are used however when building the various Docker containers that we have so we could test this by generating Docker images based on those changes. The images on Docker Hub (smarthome2cloud/smarthome-[sensors|gateway|cloud] will only be updated once the PR has been merged.

**Comment by gvancuts** [comment]
In order to make it easier to test Docker containers before Pull Request get merged, I have created a branch in the repo called `container-staging`. The content of this PR has been pushed there and Docker Hub is now configured to automatically create Docker images for this. The Docker containers including changes proposed in this PR can be pulled using the `container-staging` tag, e.g.:
```
$ sudo docker pull smarthome2cloud/smarthome-[sensors|gateway|cloud]:container-staging
```

**Comment by gvancuts** [comment]
No more comments means no objection... I'll merge this and we'll file bugs if things go south.

**Pull request merged**
